version: "3"
services:
  mongoproxy:
    container_name: mongoproxy
    #image: mongoproxy:latest
    image: mpihlak/mongoproxy:v0.2.10
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    command: ./mongoproxy --proxy 27111:mongodb:27017 --enable-jaeger --jaeger-addr jaeger:6831
    #command: ./mongoproxy --proxy 27111:mongodb-global.sandbox.int.starship.xyz:27017 --enable-jaeger --jaeger-addr jaeger:6831
    ports:
      - "9898:9898"
      - "27111:27111"
      - "27112:27112"
  mongodb:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - "27017:27017"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    logging:
      driver: none
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.8
    logging:
      driver: none
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
